# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    paths:
    - 'android/**'
    - '.github/workflows/gradle.yml'
  pull_request:
    branches: [ master ]
    paths:
    - 'android/**'
    - '.github/workflows/gradle.yml'

jobs:
  build:
    name: Gradle Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Style
        run: |
          cd android
          ./gradlew checkStyle
      - name: Lint
        run: |
          cd android
          ./gradlew lint
      - name: Build
        run: |
          cd android
          ./gradlew build
